---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtuoso
  labels: {{- include "slinky.labels" . | nindent 4 }}
    app: virtuoso
spec:
  selector:
    matchLabels:
      app: virtuoso
  template:
    metadata:
      labels:
        app: virtuoso
    spec:
      containers:
        - name: virtuoso
          image: "{{ .Values.image.virtuoso.name }}:{{ .Values.image.virtuoso.tag }}"
          env:
            - name: DBA_PASSWORD
              value: "dba"
          ports:
            - containerPort: {{ .Values.port.virtuoso }}
          volumeMounts:
            - mountPath: /data
              name: virtuoso-volume
      volumes:
        - name: virtuoso-volume
          {{- if hasKey $.Values "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.virtuoso }}
          {{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: virtuoso
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: virtuoso
      port: {{ .Values.port.virtuoso }}
      targetPort: {{ .Values.port.virtuoso }}
  selector:
    app: virtuoso
